version: '2'
services: 
  db:
    image: mysql:latest
    volumes:
      - "./.data/db:/var/lib/mysql"
      - "./conf/mysql:/etc/mysql/conf.d"
    restart: always    
    ports:
      - "10061:3306"
    environment:
      MYSQL_ROOT_PASSWORD: screwyou
      MYSQL_DATABASE: huginn
      MYSQL_USER: huginn
      MYSQL_PASSWORD: screwyou

  huginn:
    depends_on:
      - db
    image: cantino/huginn
    links:
      - db:mysql
    ports:
      - "10060:3000"
    restart: always    
    environment: 
      DATABASE_ADAPTER: mysql2
      MYSQL_PORT_3306_TCP_ADDR: mysql
      MYSQL_PORT_3306_TCP_PORT: 3306
      DATABASE_NAME: huginn
      DATABASE_USERNAME: huginn
      DATABASE_PASSWORD: screwyou
      ENABLE_INSECURE_AGENTS: "true"
      SMTP_USER_NAME: materliu
      SMTP_DOMAIM: gmail.com
      SMTP_SERVER: smtp.gmail.com
      SMTP_PASSWORD: screwyou
      EMAIL_FROM_ADDRESS: materliu@gmail.com  
      TIMEZONE: Beijing

